### ISSUE TITLE
Unable to install Extension.

### ISSUE THREAD

**Issue by theboy181** [Maschell/GhidraRPXLoader#1]
When I tried to install RPXLoader in Ghidra using Install Extensions, I don't see any file to select in any of the folders,(Release 0.6)

I can't see to get the extension installed this way, and when I put the RPX folder in the directory Extensions folder manually, I get errors about the symbols when I try to open a RPX file. I am unsure if its even working.

Please halp,

**Comment by Maschell** [comment]
Without any detailed information I can't help.
Which ghidra version are you using? Which rpx/rpl are you loading? What kind of error are you getting?

I just downloaded the newest Ghidra version (9.0.2) and tested it with the 0.6 plugin with the .rpl of OSv10 and everything worked fine.

Big complex .RPX may not work properly though, because not all intructions can be decompiled (yet)

**Comment by theboy181** [comment]
I was using the same versions. 

Were you able to use install vs just dropping into the folder?

**Comment by Maschell** [comment]
Closed without describing what the issue was and how to fix it?
